server:
  port: 8080
spring:
  profiles:
    active: prod
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    title: pokemon-gateway
    name: pokemon-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
logging:
  level:
    org:
      springframework:
        security: DEBUG
        cloud:
          gateway: DEBUG