apiVersion: v1
kind: Namespace
metadata:
  name: pogokwetter
  labels:
    name: pogokwetter
---
apiVersion: v1
kind: Service
metadata:
  name: pokemon-gateway
  namespace: pogokwetter
  labels:
    app: pokemon-gateway
    tier: backend
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
  selector:
    app: pokemon-gateway
    tier: backend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-gateway
  namespace: pogokwetter
spec:
  selector:
    matchLabels:
      app: pokemon-gateway
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: pokemon-gateway
        tier: backend
    spec:
      containers:
        - name: pokemon-gateway
          image: ghcr.io/teunbuis-semester6-pogokwetter/pokemon-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080