apiVersion: v1
kind: Namespace
metadata:
  name: pogokwetter
  labels:
    name: pogokwetter
---
apiVersion: v1
kind: Service
metadata:
  name: pokemon-gateway
  namespace: pogokwetter
  labels:
    app: pokemon-gateway
    tier: backend
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
  selector:
    app: pokemon-gateway
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-gateway
  namespace: pogokwetter
spec:
  selector:
    matchLabels:
      app: pokemon-gateway
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: pokemon-gateway
        tier: backend
    spec:
      containers:
        - name: pokemon-gateway
          image: ghcr.io/teunbuis-semester6-pogokwetter/pokemon-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pokemon-service
  namespace: pogokwetter
  labels:
    app: pokemon-service
    tier: backend
spec:
  ports:
    - port: 80
      targetPort: 8081
  selector:
    app: pokemon-service
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-service
  namespace: pogokwetter
spec:
  selector:
    matchLabels:
      app: pokemon-service
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: pokemon-service
        tier: backend
    spec:
      containers:
        - name: pokemon-service
          image: docker.io/teunbuis/pogokwetter:pokemon-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: pokemonimg-mysql
  namespace: pogokwetter
  labels:
    app: pokemonimng-mysql
    tier: backend
spec:
  selector:
    app: pokemonimng-mysql
  ports:
    - protocol: TCP
      port: 3307
      targetPort: 3307
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemonimng-mysql
  namespace: pogokwetter
spec:
  selector:
    matchLabels:
      app: pokemonimng-mysql
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: pokemonimng-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Teun
            - name: MYSQL_TCP_PORT
              value: 3307
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-mq
  namespace: pogokwetter
  labels:
    app: pokemon-gateway
    tier: backend
spec:
  selector:
    app: rabbit-mq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
    - protocol: TCP
      port: 15672
      targetPort: 15672
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-mq
  namespace: pogokwetter
spec:
  selector:
    matchLabels:
      app: rabbit-mq
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbit-mq
    spec:
      containers:
        - name: rabbit-mq
          image: rabbitmq:latest
          ports:
            - containerPort: 5672
            - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: pokemon-redis
  namespace: pogokwetter
  labels:
    app: pokemon-gateway
    tier: backend
spec:
  selector:
    app: pokemon-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-redis
  namespace: pogokwetter
spec:
  selector:
    matchLabels:
      app: pokemon-redis
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: pokemon-redis
          image: redis:latest
          ports:
            - containerPort: 6379
