name: build-docker-push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew bootJar

    - name: Login To Registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{env.REGISTRY}}
        username: ${{github.actor}}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and tag Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{env.REGISTRY}}/teunbuis-semester6-pogokwetter/pokemon-gateway:${{ github.sha }}
          ${{env.REGISTRY}}/teunbuis-semester6-pogokwetter/pokemon-gateway:latest

    - name: Publish Docker image
      run: docker push ${{env.REGISTRY}}/teunbuis-semester6-pogokwetter/pokemon-gateway:${{ github.sha }}
      
    - name: install gcloud sdk
      uses: cobraz/setup-gke-gcloud-auth-plugin@v1
    - id: auth
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.JSON_AUTH }}
        service_account: 'teun-39@handy-resolver-384812.iam.gserviceaccount.com'

    - id: get-gke-credentials
      uses: google-github-actions/get-gke-credentials@v0.4.0
      with:
        location: europe-west1
        cluster_name: pogokwetter
        
    - name: Restart deployment
      run: |
        kubectl rollout restart deployment pokemon-gateway -n pogokwetter
